server:
  port: 8088


spring:
  application:
    name: TaskManagement-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/aravinth1610/TaskManagement-config-server             
  profiles:
    active: native      


management:
  tracing:
    sampling:
      probability: 1.0  # in productionn 2.6
  endpoints:
    web:
      exposure:
        include:
        - "*" 
        